SELECT DEGREE.D_CODE, STUDENT.S_ID
FROM DEGREE INNER JOIN STUDENT
ON DEGREE.D_CODE = STUDENT.D_CODE;

SELECT S_ID FROM BRIDGE
WHERE M_CODE IN ('IFM2A10', 'CSC2A10')
GROUP BY S_ID
HAVING COUNT(DISTINCT M_CODE) = 2;

SELECT DISTINCT S_ID
FROM BRIDGE 
WHERE M_CODE IN ('IFM2A10', 'CSC2A10');

SELECT M_CODE, AVG(FINAL_MARK) AS AVE_MARK
FROM BRIDGE 
GROUP BY M_CODE;

SELECT D_CODE, D_NAME
FROM DEGREE
WHERE D_CODE NOT IN (SELECT DISTINCT D_CODE FROM STUDENT)

